name: ğŸ†‡ Release to X

on:
  create

jobs:
  tweet:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'tag' && !contains(github.event.ref, 'alpha') }}
    steps:
      - name: Tweet
        uses: nearform-actions/github-action-notify-twitter@master
        with:
          message: |
            ğ• Ant Design X just released @ant-design/x@${{ github.event.ref }} âœ¨ğŸŠâœ¨ Check out the full release note: https://github.com/ant-design/x/releases/tag/${{ github.event.ref }}
          twitter-app-key: ${{ secrets.TWITTER_API_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_API_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
